@echo off
SET TODIR=C:\Users\bmarty\AccuRev\FS_Migrate\Src
SET SSEXE="C:\Program Files (x86)\Microsoft Visual SourceSafe\ss.exe"
SET SSDIR=C:\Users\bmarty\downloads\R75
SET R75SRC=$/R75/Src
%SSEXE% get %R75SRC%/APSM/ap000035/APCR.cpp -V13 -GTU -GWR -W -GF- -GL"%TODIR%\APSM\ap000035"
%SSEXE% get "%R75SRC%/Libsrc/scrlib/RDL_ROUT.cpp" -V52 -GTU -GWR -W -GF- -GL"%TODIR%\Libsrc\scrlib"
%SSEXE% get "%R75SRC%/Mcmm/mcm00004/PRT_AP.cpp" -V14 -GTU -GWR -W -GF- -GL"%TODIR%\Mcmm\mcm00004"
%SSEXE% get "%R75SRC%/Mcmm/mcm00004/PRT_AR.cpp" -V9 -GTU -GWR -W -GF- -GL"%TODIR%\Mcmm\mcm00004"
%SSEXE% get "%R75SRC%/MyFsWp/Database/7.50e/R750eUI.sql" -V22 -GTU -GWR -W -GF- -GL"%TODIR%\MyFsWp\Database\7.50e"
%SSEXE% get "%R75SRC%/MyFsWp/Database/FMXEdits.txt" -V61 -GTU -GWR -W -GF- -GL"%TODIR%\MyFsWp\Database"
%SSEXE% get "%R75SRC%/MyFsWp/Database/Labels.txt" -V34 -GTU -GWR -W -GF- -GL"%TODIR%\MyFsWp\Database"
%SSEXE% get "%R75SRC%/MyFsWp/FSWebUI/_ScriptLibrary/FSBuiltins.js" -V67 -GTU -GWR -W -GF- -GL"%TODIR%\MyFsWp\FSWebUI\_ScriptLibrary"
%SSEXE% get "%R75SRC%/MyFsWp/FSWebUI/_ScriptLibrary/FSWebUI.js" -V71 -GTU -GWR -W -GF- -GL"%TODIR%\MyFsWp\FSWebUI\_ScriptLibrary"
%SSEXE% get "%R75SRC%/MyFsWp/FSWebUI/Builtins/ShowQueryInDataGrid.asp" -V4 -GTU -GWR -W -GF- -GL"%TODIR%\MyFsWp\FSWebUI\Builtins"
%SSEXE% get "%R75SRC%/MyFsWp/FSWebUI/Finders/FinderMain.aspx.cs" -V4 -GTU -GWR -W -GF- -GL"%TODIR%\MyFsWp\FSWebUI\Finders"
%SSEXE% get "%R75SRC%/MyFsWp/FSWebUI/Finders/FinderMain.aspx" -V22 -GTU -GWR -W -GF- -GL"%TODIR%\MyFsWp\FSWebUI\Finders"
%SSEXE% get "%R75SRC%/ObjectSDK/FSTIPlus/TransactionClient/FSTIClient.vb" -V9 -GTU -GWR -W -GF- -GL"%TODIR%\ObjectSDK\FSTIPlus\TransactionClient"
%SSEXE% get "%R75SRC%/purm/pur00013/pocr.cpp" -V5 -GTU -GWR -W -GF- -GL"%TODIR%\purm\pur00013"
%SSEXE% get "%R75SRC%/Screen/APSM.FMX" -V24 -GTU -GWR -W -GF- -GL"%TODIR%\Screen"
%SSEXE% get "%R75SRC%/Screen/PURM.FMX" -V16 -GTU -GWR -W -GF- -GL"%TODIR%\Screen"
%SSEXE% get "%R75SRC%/Sql/Src/App/Arsm/Armq/Scripts/usp_IvmcCreateNewInvoice.sql" -V20 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\App\Arsm\Armq\Scripts"
%SSEXE% get "%R75SRC%/Sql/Src/App/Arsm/Armq/Scripts/usp_IvmcUpdateIvTax.sql" -V11 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\App\Arsm\Armq\Scripts"
%SSEXE% get "%R75SRC%/Sql/Src/Install/Scripts/makescripts.dat" -V139 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\Install\Scripts"
%SSEXE% get "%R75SRC%/Sql/Src/Libsrc/SqlApplib/Scripts/usp_ProcessARINTERFACE2.sql" -V14 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\Libsrc\SqlApplib\Scripts"
%SSEXE% get "%R75SRC%/Sql/Src/Libsrc/SqlApplib/Scripts/usp_ProcessModcomIV.sql" -V19 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\Libsrc\SqlApplib\Scripts"
%SSEXE% get "%R75SRC%/Sql/Src/Libsrc/SqlApplib/Scripts/usp_UpdateCreditBal.sql" -V7 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\Libsrc\SqlApplib\Scripts"
%SSEXE% get "%R75SRC%/Sql/Src/Libsrc/SqlApplib/Scripts/usp_UpdateCustHoldStatus.sql" -V11 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\Libsrc\SqlApplib\Scripts"
%SSEXE% get "%R75SRC%/Sql/Src/Reporting/FSRDL/CUSM/CusCord.rdl" -V10 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\Reporting\FSRDL\CUSM"
%SSEXE% get "%R75SRC%/Sql/Src/Reporting/FSRDL/MOMM/MomMord.rdl" -V16 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\Reporting\FSRDL\MOMM"
%SSEXE% get "%R75SRC%/Sql/Src/Reporting/FSRDL/PURM/PurPord.rdl" -V14 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\Reporting\FSRDL\PURM"
%SSEXE% get "%R75SRC%/Sql/Src/Reporting/FSReportViewer/FSReportWeb/FSReport.aspx.cs" -V13 -GTU -GWR -W -GF- -GL"%TODIR%\Sql\Src\Reporting\FSReportViewer\FSReportWeb"